//##################################################################################################
//
//  Implementation of some funcs for ctype.h.
//
//##################################################################################################

#include <ctype.h>
/*
#undef isspace
#undef isdigit
#undef toupper
#undef isprint

int isspace(int c)
{
	return c==' ' || c=='\t' || c=='\n' || c=='\v' || c=='\f' || c=='\r';
}

int isdigit(int c)
{
	return c >= '0'  &&  c <= '9';
}

int toupper(int c)
{
	if (c >= 'a'  &&  c <= 'z')
		return c + 'A' - 'a';
	else
		return c;
}

int tolower(int c)
{
	if (c >= 'A'  &&  c <= 'Z')
		return c - 'A' + 'a';
	else
		return c;
}

int isprint(int c)
{
	return 0;
}

*/

//--------------------------------------------------------------------------------------------------
// for compatibility with uClibc-1.0.28 ctype tables
//--------------------------------------------------------------------------------------------------

const __ctype_touplow_t *__C_ctype_tolower = 0;
const __ctype_touplow_t *__C_ctype_toupper = 0;

static const __ctype_mask_t __C_ctype_b_data[] =
{
#ifdef __UCLIBC_HAS_CTYPE_SIGNED__
	/* -128  M-^@ */ 0,
	/* -127  M-^A */ 0,
	/* -126  M-^B */ 0,
	/* -125  M-^C */ 0,
	/* -124  M-^D */ 0,
	/* -123  M-^E */ 0,
	/* -122  M-^F */ 0,
	/* -121  M-^G */ 0,
	/* -120  M-^H */ 0,
	/* -119  M-^I */ 0,
	/* -118  M-^J */ 0,
	/* -117  M-^K */ 0,
	/* -116  M-^L */ 0,
	/* -115  M-^M */ 0,
	/* -114  M-^N */ 0,
	/* -113  M-^O */ 0,
	/* -112  M-^P */ 0,
	/* -111  M-^Q */ 0,
	/* -110  M-^R */ 0,
	/* -109  M-^S */ 0,
	/* -108  M-^T */ 0,
	/* -107  M-^U */ 0,
	/* -106  M-^V */ 0,
	/* -105  M-^W */ 0,
	/* -104  M-^X */ 0,
	/* -103  M-^Y */ 0,
	/* -102  M-^Z */ 0,
	/* -101  M-^[ */ 0,
	/* -100  M-^\ */ 0,
	/*  -99  M-^] */ 0,
	/*  -98  M-^^ */ 0,
	/*  -97  M-^_ */ 0,
	/*  -96  M-   */ 0,
	/*  -95  M-!  */ 0,
	/*  -94  M-"  */ 0,
	/*  -93  M-#  */ 0,
	/*  -92  M-$  */ 0,
	/*  -91  M-%  */ 0,
	/*  -90  M-&  */ 0,
	/*  -89  M-'  */ 0,
	/*  -88  M-(  */ 0,
	/*  -87  M-)  */ 0,
	/*  -86  M-*  */ 0,
	/*  -85  M-+  */ 0,
	/*  -84  M-,  */ 0,
	/*  -83  M--  */ 0,
	/*  -82  M-.  */ 0,
	/*  -81  M-/  */ 0,
	/*  -80  M-0  */ 0,
	/*  -79  M-1  */ 0,
	/*  -78  M-2  */ 0,
	/*  -77  M-3  */ 0,
	/*  -76  M-4  */ 0,
	/*  -75  M-5  */ 0,
	/*  -74  M-6  */ 0,
	/*  -73  M-7  */ 0,
	/*  -72  M-8  */ 0,
	/*  -71  M-9  */ 0,
	/*  -70  M-:  */ 0,
	/*  -69  M-;  */ 0,
	/*  -68  M-<  */ 0,
	/*  -67  M-=  */ 0,
	/*  -66  M->  */ 0,
	/*  -65  M-?  */ 0,
	/*  -64  M-@  */ 0,
	/*  -63  M-A  */ 0,
	/*  -62  M-B  */ 0,
	/*  -61  M-C  */ 0,
	/*  -60  M-D  */ 0,
	/*  -59  M-E  */ 0,
	/*  -58  M-F  */ 0,
	/*  -57  M-G  */ 0,
	/*  -56  M-H  */ 0,
	/*  -55  M-I  */ 0,
	/*  -54  M-J  */ 0,
	/*  -53  M-K  */ 0,
	/*  -52  M-L  */ 0,
	/*  -51  M-M  */ 0,
	/*  -50  M-N  */ 0,
	/*  -49  M-O  */ 0,
	/*  -48  M-P  */ 0,
	/*  -47  M-Q  */ 0,
	/*  -46  M-R  */ 0,
	/*  -45  M-S  */ 0,
	/*  -44  M-T  */ 0,
	/*  -43  M-U  */ 0,
	/*  -42  M-V  */ 0,
	/*  -41  M-W  */ 0,
	/*  -40  M-X  */ 0,
	/*  -39  M-Y  */ 0,
	/*  -38  M-Z  */ 0,
	/*  -37  M-[  */ 0,
	/*  -36  M-\  */ 0,
	/*  -35  M-]  */ 0,
	/*  -34  M-^  */ 0,
	/*  -33  M-_  */ 0,
	/*  -32  M-`  */ 0,
	/*  -31  M-a  */ 0,
	/*  -30  M-b  */ 0,
	/*  -29  M-c  */ 0,
	/*  -28  M-d  */ 0,
	/*  -27  M-e  */ 0,
	/*  -26  M-f  */ 0,
	/*  -25  M-g  */ 0,
	/*  -24  M-h  */ 0,
	/*  -23  M-i  */ 0,
	/*  -22  M-j  */ 0,
	/*  -21  M-k  */ 0,
	/*  -20  M-l  */ 0,
	/*  -19  M-m  */ 0,
	/*  -18  M-n  */ 0,
	/*  -17  M-o  */ 0,
	/*  -16  M-p  */ 0,
	/*  -15  M-q  */ 0,
	/*  -14  M-r  */ 0,
	/*  -13  M-s  */ 0,
	/*  -12  M-t  */ 0,
	/*  -11  M-u  */ 0,
	/*  -10  M-v  */ 0,
	/*   -9  M-w  */ 0,
	/*   -8  M-x  */ 0,
	/*   -7  M-y  */ 0,
	/*   -6  M-z  */ 0,
	/*   -5  M-{  */ 0,
	/*   -4  M-|  */ 0,
	/*   -3  M-}  */ 0,
	/*   -2  M-~  */ 0,
#endif /* __UCLIBC_HAS_CTYPE_SIGNED__*/
	/*   -1  M-^? */ 0,
	/*    0  ^@   */ _IScntrl,
	/*    1  ^A   */ _IScntrl,
	/*    2  ^B   */ _IScntrl,
	/*    3  ^C   */ _IScntrl,
	/*    4  ^D   */ _IScntrl,
	/*    5  ^E   */ _IScntrl,
	/*    6  ^F   */ _IScntrl,
	/*    7  ^G   */ _IScntrl,
	/*    8  ^H   */ _IScntrl,
	/*    9  ^I   */ _ISspace|_ISblank|_IScntrl,
	/*   10  ^J   */ _ISspace|_IScntrl,
	/*   11  ^K   */ _ISspace|_IScntrl,
	/*   12  ^L   */ _ISspace|_IScntrl,
	/*   13  ^M   */ _ISspace|_IScntrl,
	/*   14  ^N   */ _IScntrl,
	/*   15  ^O   */ _IScntrl,
	/*   16  ^P   */ _IScntrl,
	/*   17  ^Q   */ _IScntrl,
	/*   18  ^R   */ _IScntrl,
	/*   19  ^S   */ _IScntrl,
	/*   20  ^T   */ _IScntrl,
	/*   21  ^U   */ _IScntrl,
	/*   22  ^V   */ _IScntrl,
	/*   23  ^W   */ _IScntrl,
	/*   24  ^X   */ _IScntrl,
	/*   25  ^Y   */ _IScntrl,
	/*   26  ^Z   */ _IScntrl,
	/*   27  ^[   */ _IScntrl,
	/*   28  ^\   */ _IScntrl,
	/*   29  ^]   */ _IScntrl,
	/*   30  ^^   */ _IScntrl,
	/*   31  ^_   */ _IScntrl,
	/*   32       */ _ISspace|_ISprint|_ISblank,
	/*   33  !    */ _ISprint|_ISgraph|_ISpunct,
	/*   34  "    */ _ISprint|_ISgraph|_ISpunct,
	/*   35  #    */ _ISprint|_ISgraph|_ISpunct,
	/*   36  $    */ _ISprint|_ISgraph|_ISpunct,
	/*   37  %    */ _ISprint|_ISgraph|_ISpunct,
	/*   38  &    */ _ISprint|_ISgraph|_ISpunct,
	/*   39  '    */ _ISprint|_ISgraph|_ISpunct,
	/*   40  (    */ _ISprint|_ISgraph|_ISpunct,
	/*   41  )    */ _ISprint|_ISgraph|_ISpunct,
	/*   42  *    */ _ISprint|_ISgraph|_ISpunct,
	/*   43  +    */ _ISprint|_ISgraph|_ISpunct,
	/*   44  ,    */ _ISprint|_ISgraph|_ISpunct,
	/*   45  -    */ _ISprint|_ISgraph|_ISpunct,
	/*   46  .    */ _ISprint|_ISgraph|_ISpunct,
	/*   47  /    */ _ISprint|_ISgraph|_ISpunct,
	/*   48  0    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   49  1    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   50  2    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   51  3    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   52  4    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   53  5    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   54  6    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   55  7    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   56  8    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   57  9    */ _ISdigit|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   58  :    */ _ISprint|_ISgraph|_ISpunct,
	/*   59  ;    */ _ISprint|_ISgraph|_ISpunct,
	/*   60  <    */ _ISprint|_ISgraph|_ISpunct,
	/*   61  =    */ _ISprint|_ISgraph|_ISpunct,
	/*   62  >    */ _ISprint|_ISgraph|_ISpunct,
	/*   63  ?    */ _ISprint|_ISgraph|_ISpunct,
	/*   64  @    */ _ISprint|_ISgraph|_ISpunct,
	/*   65  A    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   66  B    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   67  C    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   68  D    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   69  E    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   70  F    */ _ISupper|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   71  G    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   72  H    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   73  I    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   74  J    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   75  K    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   76  L    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   77  M    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   78  N    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   79  O    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   80  P    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   81  Q    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   82  R    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   83  S    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   84  T    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   85  U    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   86  V    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   87  W    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   88  X    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   89  Y    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   90  Z    */ _ISupper|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*   91  [    */ _ISprint|_ISgraph|_ISpunct,
	/*   92  \    */ _ISprint|_ISgraph|_ISpunct,
	/*   93  ]    */ _ISprint|_ISgraph|_ISpunct,
	/*   94  ^    */ _ISprint|_ISgraph|_ISpunct,
	/*   95  _    */ _ISprint|_ISgraph|_ISpunct,
	/*   96  `    */ _ISprint|_ISgraph|_ISpunct,
	/*   97  a    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   98  b    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*   99  c    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*  100  d    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*  101  e    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*  102  f    */ _ISlower|_ISalpha|_ISxdigit|_ISprint|_ISgraph|_ISalnum,
	/*  103  g    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  104  h    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  105  i    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  106  j    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  107  k    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  108  l    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  109  m    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  110  n    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  111  o    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  112  p    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  113  q    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  114  r    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  115  s    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  116  t    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  117  u    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  118  v    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  119  w    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  120  x    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  121  y    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  122  z    */ _ISlower|_ISalpha|_ISprint|_ISgraph|_ISalnum,
	/*  123  {    */ _ISprint|_ISgraph|_ISpunct,
	/*  124  |    */ _ISprint|_ISgraph|_ISpunct,
	/*  125  }    */ _ISprint|_ISgraph|_ISpunct,
	/*  126  ~    */ _ISprint|_ISgraph|_ISpunct,
	/*  127  ^?   */ _IScntrl,
	/*  128  M-^@ */ 0,
	/*  129  M-^A */ 0,
	/*  130  M-^B */ 0,
	/*  131  M-^C */ 0,
	/*  132  M-^D */ 0,
	/*  133  M-^E */ 0,
	/*  134  M-^F */ 0,
	/*  135  M-^G */ 0,
	/*  136  M-^H */ 0,
	/*  137  M-^I */ 0,
	/*  138  M-^J */ 0,
	/*  139  M-^K */ 0,
	/*  140  M-^L */ 0,
	/*  141  M-^M */ 0,
	/*  142  M-^N */ 0,
	/*  143  M-^O */ 0,
	/*  144  M-^P */ 0,
	/*  145  M-^Q */ 0,
	/*  146  M-^R */ 0,
	/*  147  M-^S */ 0,
	/*  148  M-^T */ 0,
	/*  149  M-^U */ 0,
	/*  150  M-^V */ 0,
	/*  151  M-^W */ 0,
	/*  152  M-^X */ 0,
	/*  153  M-^Y */ 0,
	/*  154  M-^Z */ 0,
	/*  155  M-^[ */ 0,
	/*  156  M-^\ */ 0,
	/*  157  M-^] */ 0,
	/*  158  M-^^ */ 0,
	/*  159  M-^_ */ 0,
	/*  160  M-   */ 0,
	/*  161  M-!  */ 0,
	/*  162  M-"  */ 0,
	/*  163  M-#  */ 0,
	/*  164  M-$  */ 0,
	/*  165  M-%  */ 0,
	/*  166  M-&  */ 0,
	/*  167  M-'  */ 0,
	/*  168  M-(  */ 0,
	/*  169  M-)  */ 0,
	/*  170  M-*  */ 0,
	/*  171  M-+  */ 0,
	/*  172  M-,  */ 0,
	/*  173  M--  */ 0,
	/*  174  M-.  */ 0,
	/*  175  M-/  */ 0,
	/*  176  M-0  */ 0,
	/*  177  M-1  */ 0,
	/*  178  M-2  */ 0,
	/*  179  M-3  */ 0,
	/*  180  M-4  */ 0,
	/*  181  M-5  */ 0,
	/*  182  M-6  */ 0,
	/*  183  M-7  */ 0,
	/*  184  M-8  */ 0,
	/*  185  M-9  */ 0,
	/*  186  M-:  */ 0,
	/*  187  M-;  */ 0,
	/*  188  M-<  */ 0,
	/*  189  M-=  */ 0,
	/*  190  M->  */ 0,
	/*  191  M-?  */ 0,
	/*  192  M-@  */ 0,
	/*  193  M-A  */ 0,
	/*  194  M-B  */ 0,
	/*  195  M-C  */ 0,
	/*  196  M-D  */ 0,
	/*  197  M-E  */ 0,
	/*  198  M-F  */ 0,
	/*  199  M-G  */ 0,
	/*  200  M-H  */ 0,
	/*  201  M-I  */ 0,
	/*  202  M-J  */ 0,
	/*  203  M-K  */ 0,
	/*  204  M-L  */ 0,
	/*  205  M-M  */ 0,
	/*  206  M-N  */ 0,
	/*  207  M-O  */ 0,
	/*  208  M-P  */ 0,
	/*  209  M-Q  */ 0,
	/*  210  M-R  */ 0,
	/*  211  M-S  */ 0,
	/*  212  M-T  */ 0,
	/*  213  M-U  */ 0,
	/*  214  M-V  */ 0,
	/*  215  M-W  */ 0,
	/*  216  M-X  */ 0,
	/*  217  M-Y  */ 0,
	/*  218  M-Z  */ 0,
	/*  219  M-[  */ 0,
	/*  220  M-\  */ 0,
	/*  221  M-]  */ 0,
	/*  222  M-^  */ 0,
	/*  223  M-_  */ 0,
	/*  224  M-`  */ 0,
	/*  225  M-a  */ 0,
	/*  226  M-b  */ 0,
	/*  227  M-c  */ 0,
	/*  228  M-d  */ 0,
	/*  229  M-e  */ 0,
	/*  230  M-f  */ 0,
	/*  231  M-g  */ 0,
	/*  232  M-h  */ 0,
	/*  233  M-i  */ 0,
	/*  234  M-j  */ 0,
	/*  235  M-k  */ 0,
	/*  236  M-l  */ 0,
	/*  237  M-m  */ 0,
	/*  238  M-n  */ 0,
	/*  239  M-o  */ 0,
	/*  240  M-p  */ 0,
	/*  241  M-q  */ 0,
	/*  242  M-r  */ 0,
	/*  243  M-s  */ 0,
	/*  244  M-t  */ 0,
	/*  245  M-u  */ 0,
	/*  246  M-v  */ 0,
	/*  247  M-w  */ 0,
	/*  248  M-x  */ 0,
	/*  249  M-y  */ 0,
	/*  250  M-z  */ 0,
	/*  251  M-{  */ 0,
	/*  252  M-|  */ 0,
	/*  253  M-}  */ 0,
	/*  254  M-~  */ 0,
	/*  255  M-^? */ 0
};

// __UCLIBC_CTYPE_B_TBL_OFFSET is 128 for signed ctype
const __ctype_mask_t *__C_ctype_b = __C_ctype_b_data + __UCLIBC_CTYPE_B_TBL_OFFSET;
const __ctype_mask_t *__ctype_b   = __C_ctype_b_data + __UCLIBC_CTYPE_B_TBL_OFFSET;
